# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from SPOTAPI.models.base_model_ import Model
from SPOTAPI import util


class QuoteLinkType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None):  # noqa: E501
        """QuoteLinkType - a model defined in OpenAPI

        :param id: The id of this QuoteLinkType.  # noqa: E501
        :type id: int
        :param title: The title of this QuoteLinkType.  # noqa: E501
        :type title: str
        """
        self.openapi_types = {
            'id': int,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title'
        }

        self._id = id
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'QuoteLinkType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The quoteLinkType of this QuoteLinkType.  # noqa: E501
        :rtype: QuoteLinkType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this QuoteLinkType.


        :return: The id of this QuoteLinkType.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this QuoteLinkType.


        :param id: The id of this QuoteLinkType.
        :type id: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this QuoteLinkType.


        :return: The title of this QuoteLinkType.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this QuoteLinkType.


        :param title: The title of this QuoteLinkType.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title
