/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Person } from './person';

export interface Protagonist { 
    id: number;
    type: Protagonist.TypeEnum;
    name: string;
    link?: string;
    photo?: string;
    dateUpdate?: string;
    person?: Person;
    company?: Company;
}
export namespace Protagonist {
    export type TypeEnum = 'person' | 'company';
    export const TypeEnum = {
        Person: 'person' as TypeEnum,
        Company: 'company' as TypeEnum
    };
}