/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Protagonist } from './protagonist';
import { Reference } from './reference';
import { Theme } from './theme';

export interface Quote { 
    id: number;
    title: string;
    details?: string;
    typeID: number;
    typeTitle?: string;
    dateUpdate?: string;
    themes?: Array<Theme>;
    references?: Array<Reference>;
    authors?: Array<Protagonist>;
    quoteMains?: Array<Quote>;
    quoteSupports?: Array<Quote>;
}