/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quote } from './quote';
import { Theme } from './theme';

export interface QuoteTheme { 
    themeID: number;
    theme?: Theme;
    quoteID: number;
    quote?: Quote;
}