/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Protagonist } from './protagonist';

export interface Reference { 
    id: number;
    title: string;
    details?: string;
    url?: string;
    date?: string;
    typeID: number;
    typeTitle?: string;
    reliability?: number;
    dateUpdate?: string;
    authors?: Array<Protagonist>;
}