/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Quote } from '../model/quote';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class QuoteService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Retrieve a collection of Quote objects
     * This operation supports pagination
     * @param offset The number of items to skip before returning the results
     * @param limit The number of items to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quoteGet(offset?: number, limit?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quoteGet(offset?: number, limit?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quoteGet(offset?: number, limit?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quoteGet(offset?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/quote`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create Quote
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quotePost(body: Quote, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quotePost(body: Quote, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quotePost(body: Quote, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quotePost(body: Quote, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling quotePost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/quote`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete Quote object
     * Test
     * @param quoteID The Id of a Quote
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quotesQuoteIDDelete(quoteID: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quotesQuoteIDDelete(quoteID: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quotesQuoteIDDelete(quoteID: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quotesQuoteIDDelete(quoteID: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (quoteID === null || quoteID === undefined) {
            throw new Error('Required parameter quoteID was null or undefined when calling quotesQuoteIDDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/quotes/${encodeURIComponent(String(quoteID))}/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve a Quote object
     * Test
     * @param quoteID The Id of a Quote
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quotesQuoteIDGet(quoteID: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quotesQuoteIDGet(quoteID: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quotesQuoteIDGet(quoteID: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quotesQuoteIDGet(quoteID: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (quoteID === null || quoteID === undefined) {
            throw new Error('Required parameter quoteID was null or undefined when calling quotesQuoteIDGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/quotes/${encodeURIComponent(String(quoteID))}/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of mains quotes supported by a specific quote
     * This operation supports pagination
     * @param quoteID The Id of a Quote
     * @param offset The number of items to skip before returning the results
     * @param limit The number of items to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quotesQuoteIDMainsGet(quoteID: number, offset?: number, limit?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quotesQuoteIDMainsGet(quoteID: number, offset?: number, limit?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quotesQuoteIDMainsGet(quoteID: number, offset?: number, limit?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quotesQuoteIDMainsGet(quoteID: number, offset?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (quoteID === null || quoteID === undefined) {
            throw new Error('Required parameter quoteID was null or undefined when calling quotesQuoteIDMainsGet.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/quotes/${encodeURIComponent(String(quoteID))}/mains`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update Quote object
     * Test
     * @param body 
     * @param quoteID The Id of a Quote
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quotesQuoteIDPatch(body: Quote, quoteID: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quotesQuoteIDPatch(body: Quote, quoteID: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quotesQuoteIDPatch(body: Quote, quoteID: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quotesQuoteIDPatch(body: Quote, quoteID: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling quotesQuoteIDPatch.');
        }

        if (quoteID === null || quoteID === undefined) {
            throw new Error('Required parameter quoteID was null or undefined when calling quotesQuoteIDPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('patch',`${this.basePath}/quotes/${encodeURIComponent(String(quoteID))}/`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of supports quotes for a specific quote
     * This operation supports pagination
     * @param quoteID The Id of a Quote
     * @param offset The number of items to skip before returning the results
     * @param limit The number of items to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public quotesQuoteIDSupportsGet(quoteID: number, offset?: number, limit?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public quotesQuoteIDSupportsGet(quoteID: number, offset?: number, limit?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public quotesQuoteIDSupportsGet(quoteID: number, offset?: number, limit?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public quotesQuoteIDSupportsGet(quoteID: number, offset?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (quoteID === null || quoteID === undefined) {
            throw new Error('Required parameter quoteID was null or undefined when calling quotesQuoteIDSupportsGet.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/quotes/${encodeURIComponent(String(quoteID))}/supports`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
