/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Reference } from './reference';
import { Protagonist } from './protagonist';


export interface ReferenceAuthor { 
    referenceID: number;
    reference?: Reference;
    authorID: number;
    author?: Protagonist;
}

