/**
 * Débats IDO API
 * API of Débats IDO Project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Reference } from './reference';
import { Theme } from './theme';
import { Protagonist } from './protagonist';


export interface Quote { 
    id: number;
    title: string;
    details?: string;
    typeID: number;
    typeTitle?: string;
    dateUpdate?: string;
    themes?: Array<Theme>;
    references?: Array<Reference>;
    authors?: Array<Protagonist>;
    quoteMains?: Array<Quote>;
    quoteSupports?: Array<Quote>;
}

